// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is generated by scripts/generate_sitemap_widgets.dart

import 'package:flutter/material.dart';
import '../../presentation/pages/home_page.dart';
import '../../presentation/pages/login_page.dart';
import '../../presentation/pages/settings_page.dart';

final Map<String, Widget> generatedScreenWidgets = {
  'Login': const LoginPage(),
  'Home': const HomePage(),
  'Settings': const SettingsPage(),
};
