// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is generated by scripts/generate_sitemap_widgets.dart
// ignore_for_file: prefer_const_constructors

import 'package:flutter/material.dart';
import '../../presentation/pages/home_page.dart';
import '../../presentation/pages/login_page.dart';
import '../../presentation/pages/settings_page.dart';

final Map<String, WidgetBuilder> generatedScreenBuilders = {
  'Login': (context) => LoginPage(),
  'Home': (context) => HomePage(),
  'Settings': (context) => SettingsPage(),
};
