import 'dart:io';

void main() {
  final directory = Directory('lib/presentation/pages');
  if (!directory.existsSync()) {
    print('Directory not found: lib/presentation/pages');
    return;
  }

  // Find all .dart files
  final files = directory.listSync().whereType<File>().where((f) => f.path.endsWith('.dart')).toList();
  
  final Map<String, String> widgetImports = {};
  
  // Regex to find Widget classes
  final classRegex = RegExp(r'class\s+([A-Za-z0-9_]+)\s+extends\s+(?:StatelessWidget|StatefulWidget)');

  for (final file in files) {
    // Exclude design_canvas_page.dart to avoid rendering the canvas inside the canvas
    if (file.path.endsWith('design_canvas_page.dart')) continue;

    final content = file.readAsStringSync();
    final matches = classRegex.allMatches(content);
    for (final match in matches) {
      final className = match.group(1);
      if (className != null) {
        // Calculate import path relative to lib/core/navigation/sitemap_widgets.g.dart
        final fileName = file.path.split('/').last;
        final importPath = '../../presentation/pages/$fileName';
        widgetImports[className] = importPath;
      }
    }
  }

  final buffer = StringBuffer();
  buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
  buffer.writeln('// This file is generated by scripts/generate_sitemap_widgets.dart');
  buffer.writeln();
  buffer.writeln("import 'package:flutter/material.dart';");
  
  final uniqueImports = widgetImports.values.toSet().toList()..sort();
  for (final path in uniqueImports) {
    buffer.writeln("import '$path';");
  }
  
  buffer.writeln();
  buffer.writeln('final Map<String, Widget> generatedScreenWidgets = {');
  
  for (final entry in widgetImports.entries) {
    final className = entry.key;
    String keyName = className;
    if (className.endsWith('Page') && className != 'Page') {
      keyName = className.substring(0, className.length - 4);
    }
    buffer.writeln("  '$keyName': const $className(),");
  }
  
  buffer.writeln('};');

  // Ensure output directory exists
  final outputDir = Directory('lib/core/navigation');
  if (!outputDir.existsSync()) {
    outputDir.createSync(recursive: true);
  }

  final outputFile = File('lib/core/navigation/sitemap_widgets.g.dart');
  outputFile.writeAsStringSync(buffer.toString());
  print('Successfully generated ${outputFile.path} with ${widgetImports.length} widgets.');
}
